baseURL = 'https://ddr5-5600.github.io/'
languageCode = 'zh-tw'
defaultContentLanguage = 'zh-tw'
hasCJKLanguage = true
title = "DDR5-5600's blog"
theme = 'black-and-light'


pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "DDR5-5600's blog"
  disableWebFonts = true

[[menu.main]]
    name = "About"
    url  = "https://github.com/DDR5-5600/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
